### ISSUE TITLE
Features Todo

### ISSUE THREAD

**Issue by caelinsutch** [caelinsutch/civic-information-api-graphql-wrapper#1]
Add wrappers for endpoints:

- [ ] [electionQuery](https://developers.google.com/civic-information/docs/v2/elections/electionQuery)
- [ ] [voterInfoQuery](https://developers.google.com/civic-information/docs/v2/elections/voterInfoQuery)
- [ ] [representativeInfoByDivision](https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByDivision)
- [ ] [divisionSearch](https://developers.google.com/civic-information/docs/v2/divisions/search)
